name: Playwright Tests

on:
  schedule:
    - cron: '0 12 * * *'   # 08:00 CLT
    - cron: '0 0 * * *'    # 20:00 CLT
  workflow_dispatch:       # Permite ejecución manual

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar navegadores de Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar tests con Playwright
        run: npx playwright test

      - name: Subir reporte como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Instalar nodemailer
        run: npm install

      - name: Enviar correo si falla
        if: failure()
        run: node sendEmail.js failure
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}

      - name: Enviar correo si fue exitoso
        if: success()
        run: node sendEmail.js success
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
